### ISSUE TITLE
rate defined as ms instead of frequency

### ISSUE THREAD

**Issue by Haas11** [SalvoVirga/iiwa_stack_examples#1]
Correct me if I'm wrong but I noticed the construction of rate objects in the example package always assumes its value in [ms] as is mentioned in the comments right behind it.
The rate class is actually expecting a frequency, not a sampling time, so the examples might give some surprising/dangerous behaviour when using those default values.

As expected the lower level code in the main iiwa_stack examples do assume frequencies so all good there.

**Comment by SalvoVirga** [comment]
very true indeed, I guess I made the mistake once and dragged it with copy/paste
Thanks a lot for pointing that out, will fix it asap.
