### ISSUE TITLE
where is the robotConnected flag set?

### ISSUE THREAD

**Issue by Haas11** [SalvoVirga/iiwa_stack_examples#2]
Where is the isRobotConnected Boolean supposed to be set to true?

I can't find any mention of it on the ros or jave side, only the the iiwa_stack/iiwa_ros.cpp has a commented out method that looks related. 

It never seems to be set high, although in most cases do receive messages from the iiwa if I manually set it to true.

**Comment by SalvoVirga** [comment]
Thanks for pointing that out, I commit what should fix that.
All this exemplary repo was written quickly in one lazy evening, I honestly never thought someone would ever run this code, so I never test it myself on the robot. Probably is a good idea to do it!
I'll close this after testing

**Comment by Haas11** [comment]
yeah I figured. They're still a great way of quickly understanding what's going on.
I've noticed quite a few extra steps to take with respect to what's in the wiki.
Some more interesting than others. 
Thanks for the great work! I'll upload any and all useful code over the coming weeks to the mathworks file exchange and github.
