### ISSUE TITLE
Out of dated? 

### ISSUE THREAD

**Issue by GaspardQin** [SalvoVirga/iiwa_stack_examples#3]
Thank you for your iiwa_stack, it could be really helpful for me. But It seems that this repo is out of dated, cause it use **iiwa_msgs::SmartServoMode**, **iiwa_msgs::ConfigureSmartServo**, etc, which cannot be found in the latest master branch of iiwa_stack.

So is there are any examples of the latest version of iiwa_stack ?

Thank you very much.

**Comment by SalvoVirga** [comment]
Yes, this repo is a bit old after all the changes that were made in iiwa_stack.
I will try to update it when I find some time, meanwhile you can find some examples in the [iiwa_stack's wiki](https://github.com/SalvoVirga/iiwa_stack/wiki#features).

**Comment by GaspardQin** [comment]
Thanks a lot!
